### ISSUE TITLE
Left click hide/show not fully working in v5.0

### ISSUE THREAD

**Issue by kwalker99** [tliron/em-dash#7] opened 2018-11-27 17:05 UTC
The left click show/hide feature has stopped working reliably in v5.0...

I wish Gnome had a sensible way of being able to roll back extension versions, reminds me of stupid Apple ideas like the App store and the inability to roll back application versions...

**Comment by kwalker99** [comment] 2018-11-27 17:08
mouse scroll works, but the left click to show has definitely stopped working, left click hides an app ok, but clicking again doesn't show the app.

How do I roll back to the previous version?

**Comment by tliron** [comment] 2018-11-27 17:25
Hm, that is annoying. The recent versions fixes some things for GNOME 3.30, but maybe caused a regression. Which version of GNOME are you running?

You would get the most control over versions by installing from here on GitHub. That way you can checkout specific commits and help me debug for where exactly something breaks for you.

**Comment by kwalker99** [comment] 2018-11-27 18:18
Rolled back to v4 from a backup and left click functioning correctly again.

Just replied to the 18.10 install issue, v5 now installs ok on 18.10 and relevant to this issue,  left click shows/hides perfectly. Other extensions are still yet to be updated, so I will have to stay on 18.04 for a while longer yet. 

So is the repo a rolling version? just cloning always downloads the latest, how do I clone say v4 or v4.1 etc?

Versions as requested:
Linux 4.20.0-042000rc3-generic #201811182231 SMP
GNOME Shell 3.28.3
OpenGL core profile version string: 3.3 (Core Profile) Mesa 19.0.0-devel (git-16e4911 2018-11-27 bionic-oibaf-ppa)

**Comment by tliron** [comment] 2018-11-27 18:42
You can use `git checkout` for specific commits. Your GNOME will then use
whatever version you checked out (you just need to restart GNOME).

OK, looks like the issue has to do with my GNOME 3.30 fix ... I will try to
test on a 3.28 virtual machine.

**Comment by tliron** [comment] 2018-12-01 17:27
Thank you very much for your big report! I found the issue. I am uploading a new version to GNOME Extensions, though please be patient because it can take them 2 weeks to review...

**Comment by kwalker99** [comment] 2018-12-01 17:44
Big report lol







*From:* Tal Liron [mailto:notifications@github.com]
*Sent:* Saturday, December 01, 2018 9:28 PM
*To:* tliron/em-dash
*Cc:* Kevin Walker; Author
*Subject:* Re: [tliron/em-dash] Left click hide/show not fully working in
v5.0 (#7)



Thank you very much for your big report! I found the issue. I am uploading
a new version to GNOME Extensions, though please be patient because it can
take them 2 weeks to review...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tliron/em-dash/issues/7#issuecomment-443442592>, or mute
the thread

**Comment by tliron** [comment] 2018-12-01 19:36
Haha. :) I will leave that typo for kicks.

I would appreciate if you could test that this works for you (latest version on git) and close the bug if it's solved!

**Comment by kwalker99** [comment] 2018-12-01 19:52
yeah sure, let me download

**Comment by kwalker99** [comment] 2018-12-01 19:57
yep, fixed... I am guessing version: development, is v5.1 ;-)

**Comment by tliron** [comment] 2018-12-01 21:11
I found out the hard way that the version on the GNOME extensions site has nothing to do with mine. It simply bumps the version there every time I upload.

Anyway, will close this bug. Thank you for your help!

**Closed as completed by tliron** 2018-12-01 21:11 UTC
